// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZv-tsFXofOnj_pxqW9ehVj4ETR5FHq1Q',
    appId: '1:900978890680:web:33d4a4d945ef947535214d',
    messagingSenderId: '900978890680',
    projectId: 'unimarket-e3282',
    authDomain: 'unimarket-e3282.firebaseapp.com',
    storageBucket: 'unimarket-e3282.firebasestorage.app',
    measurementId: 'G-S2FLS2R02Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwKjRI0aw1BosgoleBtyHVTiuguknt_M',
    appId: '1:900978890680:android:2f20fc11b64bb29f35214d',
    messagingSenderId: '900978890680',
    projectId: 'unimarket-e3282',
    storageBucket: 'unimarket-e3282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Bp-DHVvzMYBRryR-jUosEmWiTsMtGP4',
    appId: '1:900978890680:ios:84fac44544597d0b35214d',
    messagingSenderId: '900978890680',
    projectId: 'unimarket-e3282',
    storageBucket: 'unimarket-e3282.firebasestorage.app',
    iosBundleId: 'com.unimarket.uniMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Bp-DHVvzMYBRryR-jUosEmWiTsMtGP4',
    appId: '1:900978890680:ios:84fac44544597d0b35214d',
    messagingSenderId: '900978890680',
    projectId: 'unimarket-e3282',
    storageBucket: 'unimarket-e3282.firebasestorage.app',
    iosBundleId: 'com.unimarket.uniMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZv-tsFXofOnj_pxqW9ehVj4ETR5FHq1Q',
    appId: '1:900978890680:web:1612825fd591e35c35214d',
    messagingSenderId: '900978890680',
    projectId: 'unimarket-e3282',
    authDomain: 'unimarket-e3282.firebaseapp.com',
    storageBucket: 'unimarket-e3282.firebasestorage.app',
    measurementId: 'G-FSXD6GYMKF',
  );
}